# Generated by Django 4.2.30 on 2026-05-09 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLanguageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_language', models.CharField(default='en-US', max_length=10, verbose_name='Primary Language Code')),
                ('secondary_language', models.CharField(default='en-US', max_length=10, verbose_name='Secondary Language Code')),
                ('industry', models.CharField(choices=[('technology', 'Technology'), ('finance', 'Finance'), ('medical', 'Healthcare'), ('education', 'Education'), ('legal', 'Legal'), ('general', 'General')], default='general', max_length=50, verbose_name='Industry')),
                ('hint_phrases', models.JSONField(default=list, verbose_name='Hint Phrases')),
                ('hints_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Hints Generated At')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='language_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_language_profiles',
            },
        ),
    ]
