# Generated by Django 4.2.30 on 2026-05-22 13:32

import accounts.models
from django.db import migrations, models
import random
import string


def generate_unique_org_keys(apps, schema_editor):
    """Assign unique org_keys to all existing users."""
    User = apps.get_model('accounts', 'User')
    existing_keys = set()
    for user in User.objects.all():
        while True:
            key = ''.join(random.choices(string.ascii_letters + string.digits, k=4))
            if key not in existing_keys:
                break
        existing_keys.add(key)
        user.org_key = key
        user.save(update_fields=['org_key'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userlanguageprofile'),
    ]

    operations = [
        # Step 1: Add the field WITHOUT unique constraint
        migrations.AddField(
            model_name='user',
            name='org_key',
            field=models.CharField(blank=True, default=accounts.models.generate_org_key, max_length=4, verbose_name='Organization Key'),
        ),
        # Step 2: Populate unique values for existing users
        migrations.RunPython(generate_unique_org_keys, migrations.RunPython.noop),
        # Step 3: Add the unique constraint
        migrations.AlterField(
            model_name='user',
            name='org_key',
            field=models.CharField(blank=True, default=accounts.models.generate_org_key, max_length=4, unique=True, verbose_name='Organization Key'),
        ),
    ]
