# Generated by Django 4.2.30 on 2026-05-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_org_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slack_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Slack ID'),
        ),
    ]
