# Generated by Django 4.2.30 on 2026-04-16 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_url', models.URLField(max_length=500, verbose_name='Meeting URL')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Meeting Title')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Meeting Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('bot_joining', 'Bot Joining'), ('in_progress', 'In Progress'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('bot_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Recall Bot ID')),
                ('full_transcript', models.TextField(blank=True, default='', verbose_name='Full Transcript')),
                ('final_summary', models.TextField(blank=True, default='', verbose_name='Final Summary')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meetings',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_speaker', models.CharField(max_length=150, verbose_name='Assignee')),
                ('task_description', models.TextField(verbose_name='Task (English)')),
                ('deadline', models.CharField(blank=True, max_length=100, null=True, verbose_name='Deadline')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='meetings.meeting')),
            ],
            options={
                'db_table': 'action_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField(verbose_name='Chunk #')),
                ('raw_text', models.TextField(verbose_name='Raw Transcript Text')),
                ('processed_json', models.JSONField(blank=True, null=True, verbose_name='LLM Output JSON')),
                ('timestamp_start', models.FloatField(default=0, verbose_name='Start Time (seconds)')),
                ('timestamp_end', models.FloatField(default=0, verbose_name='End Time (seconds)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_chunks', to='meetings.meeting')),
            ],
            options={
                'db_table': 'transcript_chunks',
                'ordering': ['chunk_index'],
                'unique_together': {('meeting', 'chunk_index')},
            },
        ),
    ]
