# Generated by Django 4.2.30 on 2026-04-29 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recall_participant_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Recall Participant ID')),
                ('name', models.CharField(max_length=150, verbose_name='Display Name')),
                ('is_speaking', models.BooleanField(default=False, verbose_name='Currently Speaking')),
                ('talk_time_seconds', models.PositiveIntegerField(default=0, verbose_name='Total Talk Time (s)')),
                ('word_count', models.PositiveIntegerField(default=0, verbose_name='Total Words Spoken')),
                ('performance_score', models.FloatField(blank=True, null=True, verbose_name='Performance Score (0-100)')),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=20, null=True, verbose_name='Sentiment')),
                ('last_quote', models.TextField(blank=True, default='', verbose_name='Last Notable Quote')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='meetings.meeting')),
            ],
            options={
                'db_table': 'speakers',
                'ordering': ['-word_count'],
                'unique_together': {('meeting', 'recall_participant_id')},
            },
        ),
        migrations.CreateModel(
            name='SpeakerAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.FloatField(default=0, verbose_name='Window Start (seconds)')),
                ('window_end', models.FloatField(default=0, verbose_name='Window End (seconds)')),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=20)),
                ('performance_score', models.FloatField(blank=True, null=True, verbose_name='Performance Score (0-100)')),
                ('summary', models.TextField(blank=True, default='', verbose_name='Window Summary')),
                ('key_points', models.JSONField(default=list, verbose_name='Key Points')),
                ('topic_coverage', models.JSONField(default=dict, verbose_name='Topic Coverage')),
                ('one_line_quote', models.TextField(blank=True, default='', verbose_name='Notable Quote')),
                ('engagement_signals', models.JSONField(default=dict, verbose_name='Engagement Signals')),
                ('raw_response', models.JSONField(blank=True, null=True, verbose_name='Raw LLM Response')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_analyses', to='meetings.meeting')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='meetings.speaker')),
            ],
            options={
                'db_table': 'speaker_analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveTranscriptSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Transcript Text')),
                ('start_time', models.FloatField(default=0, verbose_name='Start Time (seconds from meeting start)')),
                ('end_time', models.FloatField(default=0, verbose_name='End Time (seconds)')),
                ('is_final', models.BooleanField(default=True, verbose_name='Is Final Segment')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_segments', to='meetings.meeting')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='meetings.speaker')),
            ],
            options={
                'db_table': 'live_transcript_segments',
                'ordering': ['start_time'],
            },
        ),
    ]
