# Generated by Django 4.2.30 on 2026-05-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_speaker_speakeranalysis_livetranscriptsegment'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='live_language',
            field=models.CharField(default='English', max_length=50, verbose_name='Live Language'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='summary_language',
            field=models.CharField(default='English', max_length=50, verbose_name='Summary Language'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='target_topics',
            field=models.JSONField(blank=True, default=list, verbose_name='Target Topics'),
        ),
    ]
