# Generated by Django 4.2.30 on 2026-05-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_meeting_live_language_meeting_summary_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='transcription_mode',
            field=models.CharField(choices=[('auto', 'Auto (default)'), ('skip', 'Auto-detect (skip 8s warmup)'), ('hints', 'Use preferred language + AI hints')], default='auto', max_length=10, verbose_name='Transcription Mode'),
        ),
    ]
