# Generated by Django 4.2.30 on 2026-05-14 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0004_meeting_transcription_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='notification_sent',
            field=models.BooleanField(default=False, verbose_name='Notification Sent'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Notification Sent At'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items', to='meetings.speaker'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.CreateModel(
            name='TeamDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Display Name')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email Address')),
                ('slack_id', models.CharField(blank=True, default='', max_length=50, verbose_name='Slack User ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The app user who owns this directory entry', on_delete=django.db.models.deletion.CASCADE, related_name='team_directory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'team_directory',
                'ordering': ['name'],
                'unique_together': {('user', 'email')},
            },
        ),
    ]
