# Generated by Django 4.2.30 on 2026-05-18 15:51

from django.db import migrations, models
import meetings.models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_actionitem_notification_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdirectory',
            name='key',
            field=models.CharField(blank=True, default=meetings.models.generate_10_digit_key, max_length=10, verbose_name='Key'),
        ),
    ]
