# Generated by Django 4.2.30 on 2026-05-19 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_teamdirectory_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMeetingScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_score', models.FloatField(default=0, verbose_name='Performance Score')),
                ('sentiment_positive', models.PositiveIntegerField(default=0, verbose_name='Positive Segments')),
                ('sentiment_neutral', models.PositiveIntegerField(default=0, verbose_name='Neutral Segments')),
                ('sentiment_negative', models.PositiveIntegerField(default=0, verbose_name='Concern Segments')),
                ('contribution_summary', models.TextField(blank=True, default='', verbose_name='Contribution Summary')),
                ('word_count', models.PositiveIntegerField(default=0, verbose_name='Words Spoken')),
                ('talk_time_seconds', models.PositiveIntegerField(default=0, verbose_name='Talk Time (s)')),
                ('meeting_date', models.DateTimeField(verbose_name='Meeting Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_scores', to='meetings.meeting')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_scores', to='meetings.teamdirectory')),
            ],
            options={
                'db_table': 'user_meeting_scores',
                'ordering': ['-meeting_date'],
                'unique_together': {('team_member', 'meeting')},
            },
        ),
    ]
