# Generated by Django 4.2.30 on 2026-05-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_add_user_meeting_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdirectory',
            name='key',
            field=models.CharField(blank=True, max_length=14, verbose_name='Key'),
        ),
    ]
