import{useState}from'react';

// New 6-level badge system using cumulative total score
export const RANKS=[
  {min:0,    label:'Bronze',  cls:'gp-rank-bronze',  color:'#CD7F32',badge:'/badges/level_1_badge.png',level:1},
  {min:500,  label:'Iron',    cls:'gp-rank-iron',    color:'#71797E',badge:'/badges/level_2_badge.png',level:2},
  {min:1500, label:'Copper',  cls:'gp-rank-copper',  color:'#B87333',badge:'/badges/level_3_badge.png',level:3},
  {min:4000, label:'Silver',  cls:'gp-rank-silver',  color:'#C0C0C0',badge:'/badges/level_4_badge.png',level:4},
  {min:10000,label:'Gold',    cls:'gp-rank-gold',    color:'#FFD700',badge:'/badges/level_5_badge.png',level:5},
  {min:25000,label:'Crystal', cls:'gp-rank-crystal', color:'#A8E6FF',badge:'/badges/level_6_badge.png',level:6},
];

export function getRank(totalScore){return[...RANKS].reverse().find(r=>totalScore>=r.min)||RANKS[0]}
export function getNextRank(totalScore){const rnk=getRank(totalScore);return RANKS.find(r=>r.min>rnk.min)||null}
export function ptsToNext(totalScore){const next=getNextRank(totalScore);return next?next.min-totalScore:0}

export function BadgeImage({rank,size=64}){
  return <img src={rank.badge} alt={`${rank.label} Badge`} width={size} height={size} style={{objectFit:'contain',filter:`drop-shadow(0 0 8px ${rank.color}66)`}} />
}

export function initials(n=''){return n.split(' ').map(w=>w[0]).join('').toUpperCase().slice(0,2)}
export function fmtTime(s){return`${Math.floor(s/60)}m ${s%60}s`}
export function fmtDate(i){return new Date(i).toLocaleDateString('en-US',{month:'short',day:'numeric'})}
export function fmtDateFull(i){return new Date(i).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}
export function scoreColor(s){return s>=70?'#00C896':s>=40?'#FFB800':'#FF6B6B'}

export function ScoreGauge({score,size=130}){const r=(size-14)/2,c=Math.PI*2*r,o=c-(Math.min(100,Math.max(0,score))/100)*c,col=scoreColor(score);return(<svg width={size} height={size} style={{transform:'rotate(-90deg)'}}><circle cx={size/2} cy={size/2} r={r} fill="none" stroke="rgba(255,255,255,0.04)" strokeWidth="8"/><circle cx={size/2} cy={size/2} r={r} fill="none" stroke={col} strokeWidth="8" strokeDasharray={c} strokeDashoffset={o} strokeLinecap="round" style={{transition:'stroke-dashoffset 1.5s ease',filter:`drop-shadow(0 0 6px ${col})`}}/><text x={size/2} y={size/2-2} fill="#fff" fontSize="26" fontWeight="800" textAnchor="middle" dominantBaseline="central" style={{transform:'rotate(90deg)',transformOrigin:'center'}}>{Math.round(score)}</text><text x={size/2} y={size/2+16} fill="var(--text-muted)" fontSize="10" textAnchor="middle" dominantBaseline="central" style={{transform:'rotate(90deg)',transformOrigin:'center'}}>/ 100</text></svg>)}

export function RadarChart({data}){const ax=['Participation','Clarity','Sentiment','Relevance','Engagement'],cx=120,cy=120,R=90,vals=computeRadar(data),as=Math.PI*2/5,pt=(i,r)=>({x:cx+Math.sin(i*as)*r,y:cy-Math.cos(i*as)*r}),pp=vals.map((v,i)=>pt(i,(v/100)*R)).map(p=>`${p.x},${p.y}`).join(' ');return(<svg viewBox="0 0 240 240" style={{width:'100%',maxWidth:280,margin:'0 auto',display:'block'}}><defs><radialGradient id="rg"><stop offset="0%" stopColor="#6C63FF" stopOpacity="0.3"/><stop offset="100%" stopColor="#6C63FF" stopOpacity="0.05"/></radialGradient></defs>{[.25,.5,.75,1].map(r=><polygon key={r} points={Array.from({length:5},(_,i)=>pt(i,r*R)).map(p=>`${p.x},${p.y}`).join(' ')} fill="none" stroke="rgba(255,255,255,0.06)" strokeWidth="1"/>)}{ax.map((a,i)=>{const p=pt(i,R+14);return(<g key={a}><line x1={cx} y1={cy} x2={pt(i,R).x} y2={pt(i,R).y} stroke="rgba(255,255,255,0.08)"/><text x={p.x} y={p.y} fill="var(--text-muted)" fontSize="9" textAnchor="middle" dominantBaseline="central">{a}</text></g>)})}<polygon points={pp} fill="url(#rg)" stroke="#6C63FF" strokeWidth="2" style={{animation:'gpRadarPulse 3s ease-in-out infinite'}}/>{vals.map((v,i)=>{const p=pt(i,(v/100)*R);return<circle key={i} cx={p.x} cy={p.y} r="4" fill="#6C63FF" stroke="#1a1a2e" strokeWidth="2"/>})}</svg>)}
function computeRadar(h){if(!h.length)return[0,0,0,0,0];const n=h.length,as=h.reduce((s,m)=>s+m.performance_score,0)/n,aw=h.reduce((s,m)=>s+m.word_count,0)/n,ts=h.reduce((s,m)=>s+m.sentiment_positive+m.sentiment_neutral+m.sentiment_negative,0),ps=h.reduce((s,m)=>s+m.sentiment_positive,0);return[Math.min(100,n*10),Math.min(100,(aw/200)*100),ts?(ps/ts)*100:50,as,Math.min(100,as*1.1)]}

export function Sparkline({data}){const[hv,setHv]=useState(null);if(!data.length)return<div style={{color:'var(--text-muted)',fontSize:13,textAlign:'center',padding:20}}>No data</div>;const last=data.slice(-10),W=280,H=80,px=8,cW=W-px*2,pts=last.map((d,i)=>({x:px+(last.length===1?cW/2:(i/(last.length-1))*cW),y:8+(H-20)-(d.performance_score/100)*(H-20),...d})),bestIdx=pts.reduce((bi,p,i)=>p.performance_score>pts[bi].performance_score?i:bi,0),path=pts.map((p,i)=>`${i?'L':'M'} ${p.x} ${p.y}`).join(' ');return(<svg viewBox={`0 0 ${W} ${H}`} style={{width:'100%'}}><path d={`${path} L ${pts[pts.length-1].x} ${H} L ${pts[0].x} ${H} Z`} fill="url(#spG)" opacity=".3"/><path d={path} fill="none" stroke="#6C63FF" strokeWidth="2" strokeLinecap="round"/>{pts.map((p,i)=><g key={i} onMouseEnter={()=>setHv(i)} onMouseLeave={()=>setHv(null)} style={{cursor:'pointer'}}><circle cx={p.x} cy={p.y} r={hv===i?5:3} fill={hv===i?'#fff':'#6C63FF'} stroke="#1a1a2e" strokeWidth="1.5" style={{transition:'r .2s'}}/></g>)}<text x={pts[bestIdx].x} y={pts[bestIdx].y-10} textAnchor="middle" fontSize="12" style={{animation:'gpCrownBob 2s ease-in-out infinite'}}>👑</text>{hv!==null&&<g><rect x={pts[hv].x-58} y={pts[hv].y-40} width="116" height="30" rx="6" fill="rgba(10,10,30,.95)" stroke="rgba(108,99,255,.3)"/><text x={pts[hv].x} y={pts[hv].y-28} fill="#fff" fontSize="9" fontWeight="600" textAnchor="middle">{pts[hv].meeting_title}</text><text x={pts[hv].x} y={pts[hv].y-17} fill="var(--text-muted)" fontSize="8" textAnchor="middle">{fmtDateFull(pts[hv].meeting_date)} · {Math.round(pts[hv].performance_score)}</text></g>}<defs><linearGradient id="spG" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#6C63FF" stopOpacity=".5"/><stop offset="100%" stopColor="#6C63FF" stopOpacity="0"/></linearGradient></defs></svg>)}

export function SentimentArea({data,onClickPoint}){const[hv,setHv]=useState(null);if(!data.length)return<div style={{color:'var(--text-muted)',fontSize:13,textAlign:'center',padding:30}}>No sentiment data</div>;const W=560,H=180,PX=40,PY=20,cW=W-PX*2,cH=H-PY*2,pts=data.map((d,i)=>{const x=PX+(data.length===1?cW/2:(i/(data.length-1))*cW),t=d.sentiment_positive+d.sentiment_neutral+d.sentiment_negative,r=t?d.sentiment_positive/t:.5;return{x,y:PY+cH-r*cH,...d}}),line=pts.map((p,i)=>`${i?'L':'M'} ${p.x} ${p.y}`).join(' '),area=`${line} L ${pts[pts.length-1].x} ${PY+cH} L ${pts[0].x} ${PY+cH} Z`;return(<svg viewBox={`0 0 ${W} ${H}`} style={{width:'100%'}}><defs><linearGradient id="sG" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#00C896" stopOpacity=".4"/><stop offset="50%" stopColor="#8B92B8" stopOpacity=".1"/><stop offset="100%" stopColor="#FF6B6B" stopOpacity=".3"/></linearGradient></defs>{[0,.5,1].map(v=>{const y=PY+cH-v*cH;return<g key={v}><line x1={PX} x2={W-PX} y1={y} y2={y} stroke="rgba(255,255,255,.05)"/><text x={PX-6} y={y+4} fill="var(--text-muted)" fontSize="9" textAnchor="end">{v===1?'😊':v===0?'😟':'😐'}</text></g>})}<path d={area} fill="url(#sG)"/><path d={line} fill="none" stroke="#00C896" strokeWidth="2" strokeLinecap="round"/>{pts.map((p,i)=><g key={i} onMouseEnter={()=>setHv(i)} onMouseLeave={()=>setHv(null)} onClick={()=>onClickPoint&&onClickPoint(p)} style={{cursor:'pointer'}}><circle cx={p.x} cy={p.y} r={hv===i?6:4} fill={hv===i?'#fff':'#00C896'} stroke="#1a1a2e" strokeWidth="2"/><text x={p.x} y={H-4} fill="var(--text-muted)" fontSize="8" textAnchor="middle">{fmtDate(p.meeting_date)}</text></g>)}{hv!==null&&<g><rect x={pts[hv].x-65} y={pts[hv].y-44} width="130" height="34" rx="6" fill="rgba(10,10,30,.95)" stroke="rgba(108,99,255,.3)"/><text x={pts[hv].x} y={pts[hv].y-30} fill="#fff" fontSize="10" fontWeight="600" textAnchor="middle">{pts[hv].meeting_title}</text><text x={pts[hv].x} y={pts[hv].y-17} fill="var(--text-muted)" fontSize="9" textAnchor="middle">+{pts[hv].sentiment_positive} ~{pts[hv].sentiment_neutral} −{pts[hv].sentiment_negative}</text></g>}</svg>)}

export function MiniSparkline({scores}){if(!scores||scores.length<2)return null;const W=60,H=20,pts=scores.map((s,i)=>({x:4+(scores.length===1?26:(i/(scores.length-1))*(W-8)),y:2+(H-4)-(s/100)*(H-4)})),d=pts.map((p,i)=>`${i?'L':'M'}${p.x} ${p.y}`).join(' ');return<svg className="gp-lb-spark" viewBox={`0 0 ${W} ${H}`}><path d={d} fill="none" stroke="#6C63FF" strokeWidth="1.5" strokeLinecap="round" opacity=".7"/></svg>}

export function computeAchievements(h){
  return[
    {id:'fb',name:'First Blood',image:'/badges/achv_first_blood_1779469000889.png',desc:'First meeting attended',color:'#FF6B6B',unlocked:h.length>=1},
    {id:'mvp',name:'MVP',image:'/badges/achv_mvp_1779469024326.png',desc:'Scored 90+ in a meeting',color:'#FFD700',unlocked:h.some(m=>m.performance_score>=90)},
    {id:'clutch',name:'Clutch',image:'/badges/achv_clutch_1779469045837.png',desc:'High score despite negativity',color:'#FF8C00',unlocked:h.some(m=>m.sentiment_negative>m.sentiment_positive&&m.performance_score>60)},
    {id:'tp',name:'Team Player',image:'/badges/achv_team_player_1779469060818.png',desc:'3+ positive sentiment meetings',color:'#00C896',unlocked:h.filter(m=>m.sentiment_positive>m.sentiment_negative).length>=3},
    {id:'leg',name:'Legend',image:'/badges/achv_legend_1779469074464.png',desc:'10+ meetings, 80+ avg',color:'#B388FF',unlocked:h.length>=10&&(h.reduce((s,m)=>s+m.performance_score,0)/h.length)>=80}
  ]
}
export function hasStreak(h){if(h.length<3)return false;const l=h.slice(-3);return l[2].performance_score>l[1].performance_score&&l[1].performance_score>l[0].performance_score}
